locale: en_US
timezone: UTC
keyboard_layout: us
keyboard_variant: ""
packages:
  - openssh-server
mirror: ""
root_password: changeme
given_user:
  username: ubuntu
  password: ubuntu
  ssh_authorized_keys: []
  allow_sudo: true
managed_user:
  username: opnadmin
  password: opnadmin
  ssh_authorized_keys: []
  allow_sudo: true
disable_root: false
scripting_file_paths:
  global_pre_script_file: ""
  global_post_script_file: "/home/egp1042/opnlaas/config/post-install.sh"
global_kernel_params: []
global_initrd_params: []
